### PR TITLE
Support test target for local Swift Package

### PR DESCRIPTION
**Pull request by freddi-kit**
Reopen https://github.com/yonaskolb/XcodeGen/pull/1074 for some reason
Close: #1050

### CODE REVIEW

**Comment by freddi-kit** [comment]
@yonaskolb I worked https://github.com/yonaskolb/XcodeGen/pull/1074#pullrequestreview-796223123, please check it

**Review by kateinoigakukun — APPROVED** [review]

**Comment by skofgar** [comment]
@freddi-kit I had a few suggestions for your code in the previous PR: https://github.com/yonaskolb/XcodeGen/pull/1168
Would you be interested for me to re-apply it to this PR?

**Comment by freddi-kit** [comment]
Let me check it

**Comment by skofgar** [comment]
@freddi-kit I re-applied the current branch: https://github.com/yonaskolb/XcodeGen/pull/1170, I hope that helps. Please let me know if you have any questions/thoughts.

**Comment by grzegorzkrukowski** [comment]
Is there any chance this will be merged any time soon ?

**Comment by mthole** [comment]
@yonaskolb @freddi-kit 👋 What needs to be done in order to get this one merged?

**Review by yonaskolb — APPROVED** [review]
@freddi-kit, thanks for all your great work on this! 🙏

**Pull request merged**
