### PR TITLE
Enable Base Localization by default

### LINKED ISSUE #954: Xcode 12 and Base Internationalization
👋 It's another year so time for a discussion about the handling of Base Internationalisation in Xcode 12. I'm trying to wrap my head around the history of this since it seems vast so to recap:

1. #680 - Original issue of _"Enable Base Internationalization"_ warning in Xcode 11
2. #685 - Fix for original issue that adds base localisation by default
3. #694 - Addendum to handle scenarios where there is no Base.lproj directory on disk
4. #791 - Reverts last amendment and instructs us to add a **.gitkeep** file instead.

Xcode 12 has now come along and I think we need to revisit things. My unlocalised framework project is now producing the dreaded warning:

Screenshot 2020-09-22 at 13 52 17

This warning now shows despite the fact that I have zero localisable content whatsoever.

I started a new framework project in Xcode 12 to check the default behaviour and discovered that both the development language and Base are included by default:

Screenshot 2020-09-22 at 13 53 17

I then unchecked the _"Enable Base Internationalization"_ box, removed `LastUpgradeCheck` and restarted Xcode to see the warning again so my gut feeling is that we should so back to an approach where we populate `knownRegions` with `Base`, `pbxProject.developmentRegion ?? "en"`, and `sourceGenerator.knownRegions`. 

Does that sound reasonable? Or am I missing something? I can go ahead and make these changes if so

### PR DESCRIPTION
**Pull request by liamnichols**
Closes #954.

So I'm still waiting for confirmation about the approach for the linked issue, but this PR is an implementation for my proposed solution based on how Xcode 12 now behaves. 

Let me know what you think 🙏

### CODE REVIEW

**Comment by yonaskolb** [comment]
Looks good to me, though I must admit at this point the localisation settings confuse me after all the changes we've gone through.
It looks like you'll need to commit the update fixtures though for the tests.

**Comment by yonaskolb** [comment]
Does this PR keep the change requested in this issue? https://github.com/yonaskolb/XcodeGen/issues/789

**Comment by liamnichols** [comment]
Thanks @yonaskolb, I'll commit the fixture updates..

As for

> Does this PR keep the change requested in this issue? #789

No, not really... Check out my comment here though: https://github.com/yonaskolb/XcodeGen/issues/954#issuecomment-699482357

I think we have two ways around this:

1. Add a `enableBaseInternationalization` flag into the project spec that we can use to opt into including `Base`.
2. Produce warnings when running the generator that notify you if your **.storyboard** or **.nib** files are not inside **Base.lproj**

Any thoughts on that?

**Comment by liamnichols** [comment]
@yonaskolb: Fixtures have been updated thanks... Let me know what you think about.

https://github.com/yonaskolb/XcodeGen/pull/955#issuecomment-701495813 

Maybe we can keep the linked ticket open and work on warnings/project settings in separate PRs?

**Comment by liamnichols** [comment]
I'll rebase `master` and fix the the CHANGELOG.md conflict now 👍

**Review by yonaskolb — APPROVED** [review]
Thanks @liamnichols. Yes would be good to have a new PR that adds the warning back. You can use that issue to discuss further

**Comment by liamnichols** [comment]
Thanks @yonaskolb! Sorry but I didn't get a chance to update the PR description so it has auto-closed the linked issue and I can't reopen it.. Please can you do so when you get a chance

**Pull request merged**
