### PR TITLE
Remove sourceExcludes

### PR DESCRIPTION
**Pull request by bkase**
Great project!

~~`sourceExludes` should be `sourceExcludes` instead. I fixed this everywhere I could find it.~~

Removed `sourceExcludes` since it's dead for now (as discussed below)

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @bkase, good catch!`sourceExcludes` doesn't actually do anything at the moment, and is left over from when this project started. It still needs to be implemented in #5, but I think will be taking a slightly different approach than this variable, which is hinted at in #25.

Renaming this here doesn't hurt though :)

**Comment by yonaskolb** [comment]
In fact, if you want to remove these references for now, even better 😄 👍

**Comment by bkase** [comment]
Done!

**Comment by yonaskolb** [comment]
Thanks @bkase!

**Pull request merged**
