### PR TITLE
Added support for "driver-extension" and "system-extension" product types

### PR DESCRIPTION
**Pull request by vgorloff**
- Added support for "driver-extension" and "system-extension" product types [#1092](https://github.com/yonaskolb/XcodeGen/issues/1092)

### CODE REVIEW

**Comment by vgorloff** [comment]
Here is project spec file which i am currently using.

```yaml
include:
  - ../../../../mc/mcUIReusable/project.yml
  - ../../../../mc/mcAppScaffold/project.yml
name: NetFilter
configFiles:
  Debug: Configuration/project.xcconfig
  Release: Configuration/project.xcconfig
settings:
  MACOSX_DEPLOYMENT_TARGET: 10.15
fileGroups:
  - Readme.md
  - project.yml
targets:
  NetFilterApp:
    platform: macOS
    type: application
    transitivelyLinkDependencies: true
    sources:
      - path: App
      - path: Common
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: abc.xyz.Testability
      PRODUCT_NAME: NetFilter
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      COMBINE_HIDPI_IMAGES: YES
      DEPLOYMENT_LOCATION: YES
      DSTROOT: /
      INSTALL_PATH: $(LOCAL_APPS_DIR)/My
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/../Frameworks
      CODE_SIGN_ENTITLEMENTS: App/App.entitlements
      CODE_SIGN_IDENTITY: Mac Developer
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: H0M62US4J0
      PROVISIONING_PROFILE_SPECIFIER: Testability Sandbox macOS
    scheme:
      environmentVariables:
         app.runtime.loggerType: console
    dependencies:
      - target: mcUIReusable_macOS
      - target: mcAppScaffold_macOS
      - target: NetFilterExtension
        embed: true

  NetFilterExtension:
    platform: macOS
    type: system-extension
    transitivelyLinkDependencies: true
    sources:
      - path: Extension
      - path: Common
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: abc.xyz.Testability.Extension
      PRODUCT_NAME: ${PRODUCT_BUNDLE_IDENTIFIER}
      CODE_SIGN_ENTITLEMENTS: Extension/Extension.entitlements
      CODE_SIGN_IDENTITY: Mac Developer
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: H0M62US4J0
      ENABLE_HARDENED_RUNTIME: YES
      PROVISIONING_PROFILE_SPECIFIER: Testability Sandbox Extension macOS
      SKIP_INSTALL: YES
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks
    scheme: {}
    dependencies:
      - target: mcRuntime_macOS
      - target: mcFoundationLogging_macOS
```

**Review by yonaskolb — COMMENTED** [review]
Great PR, thanks @vgorloff. 
Could you please add a building example of these extensions to Tests/Fixtures/TestProject/project.yml, and then commit the diff.

**Comment by vgorloff** [comment]
Ok. I saw that folder with sample project. Will update it with system extension and driver extension.

**Review by yonaskolb — APPROVED** [review]
Awesome, thanks @vgorloff

**Pull request merged**
