### PR TITLE
Add implicit type to Dependency

### PR DESCRIPTION
**Pull request by sbarow**
As a first pass, this seems like all that is needed to add an implicit framework dependency. Are there any other edge cases we need to worry about?

I'll add some tests when I get a 👍 

Fixes: #163

### CODE REVIEW

**Comment by yonaskolb** [comment]
Nice! Have you tested it on your own project?

**Comment by sbarow** [comment]
Yeah, tested in a workspace with 5 `.xcodeproj` (workspace and projects are all generated). Works in simulator and on device.

**Comment by sbarow** [comment]
That could work. Just need to be explicit in the docs that it only applies to `framework` type.

**Comment by yonaskolb** [comment]
Yeah, there are already some options that are only applied to certain types, or have different defaults. That reminds me, can you update ProjectSpec.md?

Maybe an `implicit` boolean? Thoughts anyone? As future work may impact this decision.

**Comment by jerrymarino** [comment]
This is interesting, and perhaps adding transitive dependency logic could be useful.

Let's say I've got a project:
```
 name: SimpleProject
  targets:
   App:
     type: application
     dependencies:
      - target: Transitive
   Transitive:
     type: framework
     dependencies: 
      - target: Simple
   Simple:
     type: framework
     platform: iOS
     dependencies: 
       - implicit: Implicit.framework
```

We'd want to propagate all of the dependencies to the Application, so that they are all linked and or embedded. The `App` linker invocation would need `-framework Transitive, -framework Simple, -framework Implicit`, and the frameworks would need to be copied over.


The current way I'm achieving this is adding all transitive deps directly to top level targets, like `Application`, `Extension`, etc..
Here is what the required spec would be:
```
   App:
     type: application
     dependencies:
      - target: Transitive
      - target: Simple
      - implicit: Implicit.framework
```

Is this something that `XcodeGen` should handle internally, instead of doing it in the spec?


Based on #163 it seems like this may be related?

**Comment by yonaskolb** [comment]
@jerrymarino good point. At the moment only carthage dependencies are automatically embedded in app targets even if they aren't defined in that target, but are in a dependent target. (this isn't the case for macOS targets anymore by the way as it hasn't been added back yet after the changes in #76 removed that)

This would be possible for other dependency types as well, but I just thought there would be too many edge cases and special build settings and build scripts that people might have to do this reliably for anything else.
Perhaps another one for `ProjectSpec.options`?

**Comment by sbarow** [comment]
@jerrymarino the goal is to not have to do anything manually 😜

Regarding transitive dependencies, its an interesting one and something I have thought about. At Uber we use [buck](https://buckbuild.com) and do transitive dependency resolution manually (with the help of auditing that lets us know if we are missing a dependency in the BUCK file) I believe its a more sane approach to let the user know they are missing a dependency for a target, the other thing to consider is cyclic dependencies.

I'll take a look at both in another diff?

**Pull request closed without merging**
