### PR TITLE
Fix linking of multiple products from the same Swift Package

### PR DESCRIPTION
**Pull request by toshi0383**
## Project Spec

https://github.com/toshi0383/abceed/blob/bc1bad08ea861c737c712bb95612f51bd1aad55b/project.yml

```yml
...
  AbceedCore:
    platform: iOS
    type: framework.static
    sources:
      - AbceedCore/
    dependencies:
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
...
```

## Current Behavior

スクリーンショット 2020-04-12 20 17 25

## Expected Behavior

スクリーンショット 2020-04-12 20 16 34

## Solution

- [x] Fixed not to ignore products in `getAllDependenciesPlusTransitiveNeedingEmbedding` function.
- [x] write test for this

### CODE REVIEW

**Comment by brentleyjones** [comment]
Nice! I think this will fix https://github.com/yonaskolb/XcodeGen/issues/708.

**Comment by toshi0383** [comment]
Test fixed and added CHANGELOG entry.
Ready for review!🙌

**Comment by yonaskolb** [comment]
Thanks @toshi0383! As far as I understand this doesn't so much seem to fix transitive dependencies but rather fixing linking multiple products from the same package right?

**Comment by toshi0383** [comment]
@yonaskolb Yes! Fixed the title. Thanks for fixing changelog entry!

**Pull request merged**
