### PR TITLE
Print version with -v too

### PR DESCRIPTION
**Pull request by kastiglione**
Would it be reasonable to support `-v` in addition to `--version`?

### CODE REVIEW

**Comment by yonaskolb** [comment]
It would indeed be reasonable @kastiglione :)
It might clash with a future `--verbose` flag though. And if Commander already makes the decision to restrict to `--version` perhaps that's a good default. What do you think? Are you used to using `-v`?

**Comment by kastiglione** [comment]
Good points. Hopefully Commander wouldn't force that, but I see the concern there.

We have a version of XcodeGen that I want to upgrade to use the latest upstream release. Our XcodeGen has a `-v` flag (but not `--version`), and that flag is used by other tools to tell whether the local copy is out of date and needs an update. I could work around the `-v`/`--version` discrepancy in other ways, but if XcodeGen officially supports `-v` then that makes it easier.

Personally, I never like it when I run `-v` on some command and find out it does nothing and then try `--version` and see that it works. I can see if `-v` had some other meaning, but having no meaning seems unfortunate. For verbose, that could be `-V`, and since CAPS usually means loud, that could be suitable for verbose. I could try to add `-v` to Commander, as another approach.

Do you think XcodeGen is going to have a verbose mode? It already seems verbose/detailed as a default.

**Comment by yonaskolb** [comment]
Some good counter points :)

**Comment by kastiglione** [comment]
Thanks!

**Comment by kastiglione** [comment]
What do you think, should I open a pull request in Commander to see if they'll make `-v` an official alias for `--version`?

**Comment by yonaskolb** [comment]
Yeah, I think it's worth a PR. It should probably be done in a way in that if anyone manually adds a `-v` flag it will use that instead, and only print version as a fallback

**Pull request merged**
