### PR TITLE
Compile xcmappingmodel files instead of copying them

### PR DESCRIPTION
**Pull request by jcolicchio**
Addresses issue #833 

Might be a good idea to add a test and an example `xcmappingmodel` file in fixtures

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @jcolicchio! Could you please add a changelog entry and the tests you mention

**Comment by jcolicchio** [comment]
@yonaskolb Will take a look tonight; I'm not super familiar with the project, do you know into which folder I'd put this example `xcmappingmodel`?

**Comment by jcolicchio** [comment]
Oof built xcodegen off this branch and it's not actually working. How do I move this back into draft?

**Comment by jcolicchio** [comment]
@yonaskolb Ready for action! I ended up also making a tweak to `xcmappingmodel` inclusion to avoid it being added as a directory containing xml

**Comment by jcolicchio** [comment]
@yonaskolb Noticed some merge conflicts with a feature that makes a portion of this PR redundant, rebased and removed the unnecessary code changes. Should be good to go again 👍

**Pull request merged**
