### PR TITLE
Add support for JSON spec loading

### PR DESCRIPTION
**Pull request by rahul-malik**
If you prefer to encode your XcodeGen schema as JSON we need to update the SpecLoader in order to load it properly.

This PR uses the path extension to determine if the yaml or json loading paths should be done. I tried to add descriptive errors for failure scenarios.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks for the PR @rahul-malik!
This change is actually not needed though as json is already supported. It seems to be not that widely know but YAML is actually a superset of JSON, so a YAML decoder can in fact already decode json (but not the other way around). You can also replace any part of a yaml file with json, or just have a whole json file.

**Comment by yonaskolb** [comment]
I'll close this for now @rahul-malik. Let me know if you have any problems with loading a json spec.

**Comment by rahul-malik** [comment]
@yonaskolb - Interesting, didn't know YAML was a superset. With this change reverted I actually hit errors in Yams trying to decode a JSON file that was generated using `JSONSerialization`. Having a path that directly loads using `JSONSerialization` vs `Yams` works but I'd understand if that isn't an ideal solution.

Another thought is simply to have the `Yaml` loader fallback to `JSONSerialization` if an exception is thrown. Thoughts?

**Comment by yonaskolb** [comment]
Interesting, what errors do you get with the json file? Do you have a sample? The files I tested work, but maybe there are some edge cases in Yams.

If there are problems with it, maybe they can be fixed upstream in Yams, but otherwise maybe we do need an alternative loader. JSONSerialization can be used if the file explicitly ends in `json` otherwise use Yams

**Comment by rahul-malik** [comment]
Looks like the Yaml parser has issues with certain escape characters. Here is the output from the console:

```
                                                                                                                                                                                                               ^
  ▿ scanner: (4 elements)
    ▿ context: Optional(while parsing a quoted scalar in line 1, column 201
)
      ▿ some: while parsing a quoted scalar in line 1, column 201

        - text: "while parsing a quoted scalar"
        ▿ mark: 1:201
          - line: 1
          - column: 201
    - problem: "found unknown escape character"
    ▿ .2: 1:208
      - line: 1
      - column: 208
    - yaml: "{\"options\":{\"mirrorsFileSystem\":true},\"name\":\"HelloWorld\",\"targets\":{\"PINCache\":{\"platform\":\"iOS\",\"type\":\"library.static\",\"dependencies\":[{\"target\":\"Core\"},{\"target\":\"Arc-exception-safe\"}],\"sources\":[\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheMacros.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheObjectSubscripting.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCaching.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINDiskCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINMemoryCache.h\"]},\"PINOperation\":{\"type\":\"library.static\",\"platform\":\"iOS\",\"sources\":[\"Vendor\\/PINOperation\\/Source\\/PINOperationGroup.m\",\"Vendor\\/PINOperation\\/Source\\/PINOperationQueue.m\",\"Vendor\\/PINOperation\\/Source\\/PINOperation.h\",\"Vendor\\/PINOperation\\/Source\\/PINOperationGroup.h\",\"Vendor\\/PINOperation\\/Source\\/PINOperationMacros.h\",\"Vendor\\/PINOperation\\/Source\\/PINOperationQueue.h\",\"Vendor\\/PINOperation\\/Source\\/PINOperationTypes.h\",\"Vendor\\/PINOperation\\/pod_support\\/Headers\\/Public\\/PINOperation\\/PINOperation.h\",\"Vendor\\/PINOperation\\/pod_support\\/Headers\\/Public\\/PINOperation\\/PINOperationGroup.h\",\"Vendor\\/PINOperation\\/pod_support\\/Headers\\/Public\\/PINOperation\\/PINOperationMacros.h\",\"Vendor\\/PINOperation\\/pod_support\\/Headers\\/Public\\/PINOperation\\/PINOperationQueue.h\",\"Vendor\\/PINOperation\\/pod_support\\/Headers\\/Public\\/PINOperation\\/PINOperationTypes.h\"]},\"Arc-exception-safe\":{\"platform\":\"iOS\",\"type\":\"library.static\",\"dependencies\":[{\"target\":\"Core\"}],\"sources\":[\"Vendor\\/PINCache\\/Source\\/PINDiskCache.m\",\"Vendor\\/PINCache\\/Source\\/PINCache.h\",\"Vendor\\/PINCache\\/Source\\/PINCacheMacros.h\",\"Vendor\\/PINCache\\/Source\\/PINCacheObjectSubscripting.h\",\"Vendor\\/PINCache\\/Source\\/PINCaching.h\",\"Vendor\\/PINCache\\/Source\\/PINDiskCache.h\",\"Vendor\\/PINCache\\/Source\\/PINMemoryCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheMacros.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheObjectSubscripting.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCaching.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINDiskCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINMemoryCache.h\"]},\"Core\":{\"platform\":\"iOS\",\"type\":\"library.static\",\"dependencies\":[{\"target\":\"PINOperation\"}],\"sources\":[\"Vendor\\/PINCache\\/Source\\/PINCache.m\",\"Vendor\\/PINCache\\/Source\\/PINMemoryCache.m\",\"Vendor\\/PINCache\\/Source\\/PINCache.h\",\"Vendor\\/PINCache\\/Source\\/PINCacheMacros.h\",\"Vendor\\/PINCache\\/Source\\/PINCacheObjectSubscripting.h\",\"Vendor\\/PINCache\\/Source\\/PINCaching.h\",\"Vendor\\/PINCache\\/Source\\/PINDiskCache.h\",\"Vendor\\/PINCache\\/Source\\/PINMemoryCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheMacros.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCacheObjectSubscripting.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINCaching.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINDiskCache.h\",\"Vendor\\/PINCache\\/pod_support\\/Headers\\/Public\\/PINCache\\/PINMemoryCache.h\"]}}}"
```

**Comment by yonaskolb** [comment]
Do you know what the escape character is? 
Does your json pass a json validator? Something like https://jsonlint.com

**Comment by rahul-malik** [comment]
@yonaskolb - The JSON was actually created from a Swift dictionary (and objects conforming to Codable) using `JSONSerialization` so I'm fairly confident it's correct. I'll see if i can get the escape character

**Comment by yonaskolb** [comment]
As a side note I'm curious to hear about the workflow in your use case. You're spitting out json from swift and then using that in XcodeGen? Sounds interesting :)

**Comment by rahul-malik** [comment]
Yep - we're experimenting with transpiling existing build configurations into XcodeGen directly. Expect PRs over the next week :)

**Comment by yonaskolb** [comment]
Sounds cool. Not 100% sure what you mean there, but look forward to your ideas and PR’s 😀👍

**Pull request closed without merging**
