### PR TITLE
Fix multiple targets named 'Core' in: GraphViz, XcodeGen

### LINKED ISSUE #1048: Multiple targets named 'Core' in: GraphViz, XcodeGen
When install XcodeGen via Swift PM, Xcode says "Multiple targets named 'Core' in: GraphViz, XcodeGen".
Please consider to rename 'Core' to 'XcodeGenCore' as a workaround.

```swift
// swift-tools-version:5.3

import PackageDescription

let package = Package(
  name: "build-tools",
  platforms: [.macOS(.v10_11)],
  dependencies: [
    .package(url: "https://github.com/yonaskolb/xcodegen", from: "2.0.0"),
  ],
  targets: [.target(name: "BuildTools", path: "")]
)
```

### GraphViz/Package.swift

```swift
// swift-tools-version:5.2
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "GraphViz",
 ...
    targets: [
        .systemLibrary(name: "Clibgraphviz", pkgConfig: "libcgraph", providers: [
            .brew(["graphviz"]),
            .apt(["graphviz-dev"])
        ]),
        .target(
            name: "GraphViz",
            dependencies: ["Core", "DOT", "Builder", "Tools"]),
        .target(
            name: "Core",
            dependencies: []),
...
    ]
)
```

### XcodeGen/Package.swift

```swift
// swift-tools-version:5.0

import PackageDescription

let package = Package(
    name: "XcodeGen",
...
    targets: [
        .target(name: "XcodeGen", dependencies: [
            "XcodeGenCLI",
            "Version",
        ]),
   ...
        .target(name: "Core", dependencies: [
            "PathKit",
            "Yams",
        ]),
 ...

```

### PR DESCRIPTION
**Pull request by d-date**
Fix #1048

### CODE REVIEW

**Comment by freddi-kit** [comment]
You may need to change other old name imports, please refer https://github.com/yonaskolb/XcodeGen/compare/fix/spm-Core#diff-ac563a49106c2d342e331e34d932ba62ffa0ad0ceebce6edfb78a4efbc31cb6f

**Review by freddi-kit — APPROVED** [review]
LGTM

**Comment by freddi-kit** [comment]
Ops sorry, Could you help adding CHAGELOG.md to your changes? https://github.com/yonaskolb/XcodeGen/blob/master/CHANGELOG.md

**Comment by yonaskolb** [comment]
Thanks @d-date, closing in favour of https://github.com/yonaskolb/XcodeGen/pull/1057

**Pull request closed without merging**
