### PR TITLE
Set xcodeproj path in project.xcworkspace/contents.xcworkspacedata

### PR DESCRIPTION
**Pull request by ken0nek**
Set xcodeproj path in `xxx.xcodeproj/project.xcworkspace/contents.xcworkspacedata`

It follows the Xcode behavior.

## Example

```diff
-      location = "self:">
+      location = "self:TestProject.xcodeproj">
```

### CODE REVIEW

**Comment by brentleyjones** [comment]
Thank you @ken0nek! Can you please add a Changelog entry as well?

**Comment by ken0nek** [comment]
> Thank you @ken0nek! Can you please add a Changelog entry as well?

@brentleyjones Thank you for the review! I updated `CHANGELOG.md`.

**Comment by 0x6A75616E** [comment]
I'm using version 2.15.1

Every time I run xcodegen, the file noted above gets updated to:

```
location = "self:TestProject.xcodeproj">
```

Then as soon as Xcode runs, it gets set to 

```
location = "self:TestProject.xcodeproj">
```

What do I need to change in order to keep these in sync?

**Comment by yonaskolb** [comment]
Hi @0x6A75616E, not sure if you mistyped something but those look the same to me

**Pull request merged**
