### PR TITLE
Fixed build phase of `none` not being applied to folders

### LINKED ISSUE #287: BuildPhase "none" not possible for folders
Adding a folder without copying it (so having no Target Membership) does not work:

```
- path: Carthage/Checkouts
   buildPhase: none
   type: folder
```

setting buildPhase to headers seems to have the effect, but it seems wrong 😉

### PR DESCRIPTION
**Pull request by yonaskolb**
Fixes #287

### CODE REVIEW

**Comment by Lutzifer** [comment]
works for me when running

mint run git@github.com:yonaskolb/XcodeGen.git@no_build_phase_folders

**Comment by yonaskolb** [comment]
Cool

And great example of another good use for Mint :smile: 
(Curious why you don't go with the shorter `mint run yonaskolb/XcodeGen@no_build_phase_folders`?)

**Comment by Lutzifer** [comment]
> why you don't go with the shorter  `mint run yonaskolb/XcodeGen@no_build_phase_folders`

because I typed the name myself at the first try, wrote xcodegen instead of XcodeGen and got a git password prompt. then just copied the ssh address and went with that.

Long story short:
`mint run yonaskolb/XcodeGen@no_build_phase_folders` works
`mint run yonaskolb/xcodegen@no_build_phase_folders` doesn't

**Comment by yonaskolb** [comment]
That's weird, works for me (though not that exact command right now as the branch doesn't exist anymore)
So this doesn't work for you?
```
mint run yonaskolb/xcodegen@master
```
How is your git case sensitive? You're not on Linux are you?

**Comment by Lutzifer** [comment]
ok, ignore what I said, there was an additional k in your name 😉
should have run the above commands once again...

**Pull request merged**
