### PR TITLE
Update XcodeProj to 7.10.0

### LINKED ISSUE #821: SPM Build Failure
Getting build failures with SPM on the latest version using Xcode 11.4.0.

```
[17:20:12]: Exit status of command 'mint bootstrap' was 1 instead of 0.
🌱 Cloning XcodeGen 2.15.0
🌱 Resolving package
error: because no versions of XcodeProj match the requirement 7.8.0 and root depends on XcodeProj 7.8.0, version solving failed.
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve XcodeGen 2.15.0 with SPM
```

### PR DESCRIPTION
**Pull request by soffes**
This fixes #821

### CODE REVIEW

**Comment by soffes** [comment]
Looks like it removed some empty tags in a fixture test. Maybe that's okay? I'm not familiar enough with the format to know.

I can say, my whole team is using this version and it's working fine for our project :)

**Comment by yonaskolb** [comment]
Thanks @soffes. Could you please add a changelog entry, and as @acecilia says run the tests and then commit the updated fixtures. The fixtures serve as integration tests.

Removing those empty tags is fine. There is regular maintanance work in XcodeProj to make sure there are as few diffs as possible between the written project and how Xcode saves the project. Xcode keeps subtly changing the way it writes files, making this a losing battle 😄

**Comment by yonaskolb** [comment]
Merging this in it's current state and will fix up in master, just to get this hotfix out

**Comment by yonaskolb** [comment]
Released in 2.15.1

**Comment by acecilia** [comment]
@yonaskolb you are on fire 👏👏👏

**Comment by soffes** [comment]
Thanks for doing this! Sorry I was away from my computer this afternoon!

**Pull request merged**
