### PR TITLE
Extend possible paths for SettingsPresets

### PR DESCRIPTION
**Pull request by SofteqDG**
* Search for presets in Bundle.main.resourcesPath dir (if exists)

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @SofteqDG. Is this for using XcodeGenKit as a dependency, or what is your workflow here?

**Comment by SofteqDG** [comment]
> Thanks @SofteqDG. Is this for using XcodeGenKit as a dependency, or what is your workflow here?

Hello. Yes, it is for XcodeGenKit as a dependency. I'm using XcodeGenKit as SPM dependency and need to include presets in app bundle to make my app work on other macs.

**Comment by SofteqDG** [comment]
@yonaskolb,
Hey. Any thoughts on this change? Can it be merged?

**Review by yonaskolb — COMMENTED** [review]
Sorry for the late reply on this @SofteqDG. I'm merging this now, I'll update the changelog entry as well.
Having to do this should be negated by implementing https://github.com/yonaskolb/XcodeGen/issues/1267

Your use case sounds cool 🙂

**Pull request merged**
