### PR TITLE
Fix #784 Swift Package Manager (Embed & Sign) for dynamic packages.

### LINKED ISSUE #784: Dependencies: SPM dynamic dependency embed & sign
Similar to #271 but for Swift Package Manager dynamic dependencies declared like:

```swift
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "Components",
    platforms: [
        .iOS(.v12),
    ],
    products: [
        .library(name: "Components", type: .dynamic, targets: ["Components"]),
    ],
    targets: [
        .target(name: "Components", dependencies: []),
    ],
    swiftLanguageVersions: [.v5]
)
```

My project.yml is like:
```yaml
    type: application
    platform: iOS
    sources: Sources
    dependencies:
      - package: Components
        embed: true
```

I want my dynamic SPM dependency as Embed & Sign for application target:

Captura de pantalla 2020-02-19 a las 16 35 06

To be included here:

Captura de pantalla 2020-02-19 a las 16 35 34

@yonaskolb can you help me with config? Thanks! 😃

### PR DESCRIPTION
**Pull request by alexruperez**
Swift Package Manager dynamic dependencies declared like:

```swift
.library(name: "MyLib", type: .dynamic, targets: ["MyLib"])
```

Are embedded (**Embed & Sign** or **Embed Without Signing** if `codeSign: false`) when you declare `embed: true` in package dependency definition:

Captura de pantalla 2020-02-19 a las 16 35 06

And included here:

Captura de pantalla 2020-02-19 a las 16 35 34

### CODE REVIEW

**Comment by JesusMartinAlonso** [comment]
It would be great if this PR could be approved soon! Thanks @alexruperez for the contribution! :)

**Comment by brentleyjones** [comment]
@alexruperez Thanks for the fix! Can you update the tests and include the updated test fixtures as well? Also, can you add a Changelog entry?

**Comment by TotaX** [comment]
great work @alexruperez :) thanks for taking time to fix it..

**Comment by yonaskolb** [comment]
Thanks for the PR @alexruperez!
Currently this PR embeds all Swift packages by default which is not I think what we want. You can see this in the test failure. We either need a way to tell if a package library is static or dynamic, or only embed if it’s been defined explicitly in the spec. The current embed property defaults to yes for application targets as can be seen above your change. We can create our own property for swift package dependencies that defaults to false
```swift
 let embed = dependency.embed ?? false
```
Why do you think? I more thorough solution would be to check the framework itself for a good default.

In addition could you please:
- add a changelog entry
- add a package with an embedded dynamic library to the SPM fixture https://github.com/yonaskolb/XcodeGen/blob/master/Tests/Fixtures/SPM/project.yml
- run the tests and check in the updated generated fixtures
- ideally we’d have a unit test for this too if you have the time

Thanks!

**Comment by alexruperez** [comment]
Thanks for the feedback @yonaskolb. Added changelog entry and fixtures updates.

Also SPM dependencies are embedded only when `embed: true` is declared in the `project.yml`

Does this fit for you?

**Comment by yonaskolb** [comment]
Released in 2.14.0

**Pull request merged**
