### PR TITLE
Fix duplicate build scripts being generated when using target templates

### PR DESCRIPTION
**Pull request by nivanchikov**
This PR fixes duplicate builds scripts issue described in #574.

I haven't experienced any issues with other properties being duplicated except for the build scripts when using the same target template for several targets.

The change attempts to generate a unique set of build scripts for each build phase based on `BuildScript` equality checks.

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks @nivanchikov. Do you have a test case that would break without this change?

**Comment by nivanchikov** [comment]
@yonaskolb sorry, you mean a unit test or a test project?

**Comment by yonaskolb** [comment]
A unit test would be great

**Comment by haritowa** [comment]
@nivanchikov hi, thanks a lot. As far as I can see, your PR solves duplicates issue only for build scripts. Unfortunately, this issue spreads on other Target props. I'll try to find time to write some test cases, so it will be easier to narrow the root cause and deliver proper fixes ^_^

**Comment by yonaskolb** [comment]
As @haritowa says this may just be a symptom of a larger issue. 
@nivanchikov does your setup include a spec multiple times? We can take the conversation to #574

**Comment by nivanchikov** [comment]
@yonaskolb yes, exactly - I have a base spec which is included by several other specs. Thus I suppose this PR can be closed in favor of work being done in #574

**Pull request closed without merging**
