### PR TITLE
Include unique file only once

### LINKED ISSUE #574: Target template duplications
I have an issue when target template properties are duplicated each time `yml` file is included. 
Here is my sample setup:

```.
├── A
│   ├── Sources
│   │   └── AClass.swift
│   └── project.yml
├── B
│   ├── Sources
│   │   └── BClass.swift
│   └── project.yml
└── baseProject.yml

4 directories, 5 files
```

`baseProject.yml` contains target template `Core`:
```name: BaseProject
targetTemplates:
  Core:
    platform: iOS
    type: framework
    preBuildScripts:
      - name: Swifty Mocky
        script: echo "123"
```

Both `A/project.yml` and `B/project.yml` has an `- ../baseProject.yml` include. `xcodegen` invocation against `B/project.yml` leads to duplicated properties(build scripts, for example) for any target, that have the `Core` template.

Duplicated Build Scripts

[Sample Project](https://github.com/yonaskolb/XcodeGen/files/3118139/project.zip)

### PR DESCRIPTION
**Pull request by haritowa**
Fixes #574
Closes #577

### CODE REVIEW

**Comment by haritowa** [comment]
@nivanchikov, could you test this PR against your case from the #577

**Comment by yonaskolb** [comment]
Thanks @haritowa! This is great if it closes #574 #599 and #577
Could you fix conflicts and add a changelog entry also

**Comment by haritowa** [comment]
@yonaskolb done, but #574 is a separate issue and out of scope

**Comment by yonaskolb** [comment]
Thanks @haritowa, still need a changelog entry before this can be merged

**Comment by nivanchikov** [comment]
@haritowa can you please add a changelog? Would be awesome to get this PR merged

**Pull request merged**
