### PR TITLE
Files sorted by type

### PR DESCRIPTION
**Pull request by yukkobay**
## Motivation
I want to sort files sort by type as we can with Xcode.

## Description
I added code to sort by type before sorting by name.
We should consider adding as optional. Do you have any ideas?

### CODE REVIEW

**Comment by toshi0383** [comment]
fyi you can use other script to do it.
https://github.com/toshi0383/scripts/blob/master/xcode/sort-Xcode-project-file

Maybe we can consider plugin feature to apply whatever modification to the generated output by XcodeGen, before actually write to the disk.(maybe in the future)

**Comment by toshi0383** [comment]
BTW I’m thumb-up to this change. Nice work @yukkobay 👍

**Comment by yonaskolb** [comment]
Thanks for the PR @yukkobay. I'm not comfortable making this the default, but we could add a `SpecOptions.SortType` enum with `name` and `type` cases with the default being `name`

**Comment by yonaskolb** [comment]
@toshi0383 and yes, agree that having some way to modify the XcodeProj in Swift, before it is generated would be great. If you have any good ideas around how to do this, let me know

**Comment by yukkobay** [comment]
@yonaskolb Thank you for reviewing!
I agree with you. I'll try it! 💪

**Pull request closed without merging**
