### PR TITLE
Enable adding local Swift packages to the project root

### LINKED ISSUE #1209: set 'no group' for local packages
Is there a way to set no group for a local package?  
At the moment there's the `group` option for local packages and [`localPackagesGroup`](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#local-package), but neither can be set to something that allows a package to sit at the projects root without a group.

### PR DESCRIPTION
**Pull request by hiltonc**
This enables adding local Swift packages to the project root. This can be done in one of two ways:

1. Use a `""` group for a package:

```
packages:
  MyPackage:
    path: MyPackage
    group: ""
```

2. Use `""` for the `localPackagesGroup` option:

```
options:
  localPackagesGroup: ""
```

Resolves #1209

### CODE REVIEW

**Review by MartinP7r — APPROVED** [review]
LGTM 👍🏼

**Comment by yonaskolb** [comment]
Thank you for this @hiltonc. Could you resolve the conflicts and make sure it still works after https://github.com/yonaskolb/XcodeGen/pull/1417 was merged

**Comment by OmranK** [comment]
Would this solution allow you to have Xcode project with local packages generated like this?
Screenshot 2024-02-25 at 6 42 49 AM

**Comment by hiltonc** [comment]
@yonaskolb I've resolved conflicts, tests pass, and I manually verified both configuration options.

**Pull request merged**
