### PR TITLE
Homebrew support

### PR DESCRIPTION
**Pull request by pepibumur**
Solves #15

### CODE REVIEW

**Comment by pepibumur** [comment]
Here it is @yonaskolb

**Comment by yonaskolb** [comment]
Awesome! Is this tested and works?
How do we add this as an official homebrew package?

**Comment by pepibumur** [comment]
Yes @yonaskolb, I tried it locally and it works. Do you think we should document/automate the release process somewhere?
Regarding what to do to make it an official package, first of all, it has to meet all [this](https://docs.brew.sh/Acceptable-Formulae.html) requirements. Once it meets all of them, we can commit the formula to this repository https://github.com/Homebrew/homebrew-core. 

Before merging this there are a couple of things that I'd do:
- Add a method to the formula that verifies that the installation was successful.
- Check the acceptable criteria and make sure we stick to it.

**Comment by yonaskolb** [comment]
For the installation check, we should add a version command that prints the current version. So we can merge this after a 0.2.0 release
Is there anything in the criteria we fall short on?

**Comment by pepibumur** [comment]
[Homebrew support](https://trello.com/c/4NzcHxGn/16-homebrew-support)

**Comment by pepibumur** [comment]
Ready @yonaskolb. Once this https://github.com/Homebrew/homebrew-core/pull/16311 gets merged, we can merge this one. The formula will be in homebrew-core and developers can install the tool with:

```
brew install XcodeGen
```
_(without adding any Tap repository)_

**Comment by yonaskolb** [comment]
Fantastic 🎉

**Comment by pepibumur** [comment]
MM @yonaskolb there was no update on the homebrew-core repo. Are you ok if we add the formula to this repository? It'll be easier to post updates if we can do it directly in this repository.

**Comment by yonaskolb** [comment]
@pepibumur Yeah, add the formula here 👍

**Comment by pepibumur** [comment]
This is ready to be merged @yonaskolb

**Comment by yonaskolb** [comment]
@pepibumur I'm getting errors using the homebrew installation instructions. Running:
```
brew tap yonaskolb/XcodeGen git@github.com:yonaskolb/XcodeGen.git
```
leads to the error:
```
Cloning into '/usr/local/Homebrew/Library/Taps/yonaskolb/homebrew-xcodegen'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Failure while executing: git clone git@github.com:yonaskolb/XcodeGen.git /usr/local/Homebrew/Library/Taps/yonaskolb/homebrew-xcodegen --depth=1
```

**Comment by yonaskolb** [comment]
Looks like changing the url works
```
brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
```
I'll fix this in the readme

**Comment by pepibumur** [comment]
Cool! I think it depends on your git setup. In my case https was failing. I wonder if there's a way to tell Homebrew to use either https or ssh based on your local setup. :/

**Pull request merged**
